dependencies:
  - name: kube-state-metrics
    version: "2.8.*"
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: kubeStateMetrics.enabled
  - name: prometheus-pushgateway
    version: "1.10.1"
    repository: "https://prometheus-community.github.io/helm-charts"
    condition: prometheus-pushgateway.enabled
