apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: prometheus-bucket
spec:
  backendType: vault
  kvVersion: 2
  vaultMountPoint: kubernetes
  vaultRole: k8s-secrets
  data:
    - key: k8s/data/secrets/sa-metrics
      name: sa-name
      property: sa-name
    - key: k8s/data/secrets/sa-metrics
      name: sa-key
      property: sa-key
  template:
    type: Opaque
    data:
      bucket.yaml: |
        type: AZURE
        <%= yaml.dump(JSON.parse(data.sa-name)) %>