apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: prometheus-bucket
spec:
  backendType: vault
  data:
    - key: k8s/data/secrets/sa-metrics
      name: sa-name
      property: sa-name
    - key: k8s/data/secrets/sa-metrics
      name: sa-key
      property: sa-key
  template:
    type: Opaque
    data:
      bucket.yaml: |
        type: AZURE
        config:
          storage_account: "<%= yaml.dump(JSON.parse(data.sa-name)) %>"
          storage_account_key: "<%= yaml.dump(JSON.parse(data.sa-key)) %>"
          container: "thanos"
          endpoint: ""
          max_retries: 3

  vaultMountPoint: kubernetes
  vaultRole: k8s-secrets