---
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: prometheus-bucket
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: prometheus-bucker
  data:
  - secretKey: sa-name
    remoteRef:
      key: k8s/data/secrets/sa-metrics
      property: sa-name  
  - secretKey: sa-key
    remoteRef:
      key: k8s/data/secrets/sa-metrics
      property: sa-key