---
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: prometheus-bucket
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: prometheus-bucket
  data:
  - secretKey: sa-name
    remoteRef:
      key: k8s/data/secrets/sa-metrics
      property: sa-name  
  - secretKey: sa-key
    remoteRef:
      key: k8s/data/secrets/sa-metrics
      property: sa-key
  template:
    data:
      bucket.yaml: |
        type: AZURE
        config:
          storage_account: "{{`{{ .sa-name | toString }}`}}"
          storage_account_key: "{{`{{ .sa-key | toString }}`}}"
          container: "thanos"
          endpoint: ""
          max_retries: 3


---
apiVersion: external-secrets.io/v1alpha1
kind: SecretStore
metadata:
  name: vault-backend
spec:
  provider:
    vault:
      server: "http://vault.tooling.svc:8200"
      path: "k8s"
      version: "v2"
      auth:
        # Authenticate against Vault using a Kubernetes ServiceAccount
        # token stored in a Secret.
        # https://www.vaultproject.io/docs/auth/kubernetes
        kubernetes:
          # Path where the Kubernetes authentication backend is mounted in Vault
          mountPath: "kubernetes"
          # A required field containing the Vault Role to assume.
          role: "k8s-secrets"