apiVersion: v2
name: prometheus
description: A Helm chart for Kubernetes

type: application
version: 0.1.0

dependencies:
- name: kube-prometheus-stack
  version: "15.4.5"
  repository: "https://prometheus-community.github.io/helm-charts"
